### ISSUE TITLE
"pip install Tkinter" command

### ISSUE THREAD

**Issue by just-rahim** [razewerz/auto-multi-executable-files-runner#1]
It's not effective to run this command Everytime you execute the script. In case there's no internet it's problem.

**Comment by razewerz** [comment]
1. isn't a problem at all if there isn't an internet connection for your device, because the system automatically recognizes that you installed the package before, you can try it, just disconnect from the internet connection and run the code, you will see the terminal replied with  `Requirement already satisfied` .
2. thank you for reminding me btw still a good idea for a clean terminal etc 
3. I'll edit it by the following script :
	```
import dropbox
except:ImportError(
	system('pip install dropbox'))	  
```

**Comment by razewerz** [comment]
1. isn't a problem at all if there isn't an internet connection, because the system will automatically recognize that you installed the library before, you can try it just disconnect from the connection, and the terminal pup out with  `Requirement already satisfied` 
2. btw the idea is still good for a clean terminal etc. THANK YOU
3. I'll edit it with the following code :  
```
try:
	import dropbox
except:ImportError(
	system('pip install dropbox'))	
```
